### ISSUE TITLE
[Question] Redundancy state changes

### ISSUE THREAD

**Issue by phil-dileo** [aristanetworks/EosSdk#13]
Hi, just wondering if it'd be possible to write an agent that reacted to switchover state changes? EG the states that exist within the REDUNDANCY Mib:
- protocol
- state
- switchover reason

Thanks!

**Comment by rmadsen** [comment]
Hi Phil,
We don't expose a handler for this information yet. I do have a question for you about how you plan on using this information? Right now, all EOS SDK agents started via the `daemon` command run on the active supervisor. When there is a switchover, the agent is restarted on the standby sup. In this flow, the agent would never receive the switchover callback, because it will be busy being restarted. Would you want to know that a switchover *had* happened (after you restart) or do you want the agent running on both sups simultaneously? Or is there some other behavior that you'd prefer?

**Comment by rmadsen** [comment]
Closing this issue for now. We can re-open it if we find a use-case for switchover handlers.
