### ISSUE TITLE
agent crash on connect to Sysdb

### ISSUE THREAD

**Issue by hubertsokolowskintl** [aristanetworks/EosSdk#28]
Hi,

My agent is crashing when running during connection to Sysdb with these messages:
2017-06-01 17:32:24.866059 Using external Socket tbl://sysdb/+n
2017-06-01 17:32:24.866109 Using externally set fd: 7
setsockopt failed Socket operation on non-socket(88), fd = 7
getsockopt failed Socket operation on non-socket(88), fd = 7
./NboAttrLogSocketOutSm.tin:791: : Assertion `false' failed.
Unix Time: 1496338344: Process 7537 died with signal 6 (SIGABRT) errno 0 code -6 (unknown)
The killer was pid 7537 (myself) with uid 0
Backtrace: (most recent first)
/lib/libtac.so.0(_ZN13SignalHandler13signalHandlerEiP9siginfo_tPv+0x21f)[0xf686e75f]
[0xf7747490]
[0xf77474b0]
/lib/libc.so.6(gsignal+0x49)[0xf73e8169]

I tried writing a very simple agent based on RandomRouter.cpp example that only waits for on_initialized and prints hello from there and it works, it does not crash. My agent is similar, but I have some other dependencies and different 3rd party libraries linked in.  I am using your cross-compiler (fc18.tar.gz) to compile both agents. In my agent I am not doing anything special with SDK apart from running the SDK's main_loop in a separate thread and waiting for it until on_initialized is called.
However I noticed that my agent gets some parameters passed in when run, I printed them and they are:
1 argv --sysdbfd=6
2 argv --agenttitle=psmenet-psmenet
3 argv --demuxerOpts=53198206421899,53198205733727,tbl://sysdb/+n,Sysdb (pid:175

I checked that the simple agent is not getting any attributes. 
I created both daemons in the same way by creating profile in Sysdb using your instructions. I am running both daemon in the same way by running 'no shutdown' from CLI. 
Can you tell me why my agent is getting these attributes?
Maybe it will tell me something about why it is crashing.

Regards,
Hubert

**Comment by ruferp** [comment]
Both agents should have received those "extra arguments", they are needed since release 4.16.6 in order to connect to Sysdb correctly. 
Can you check if "ldd <your-simple-agent> | grep libeos" has a match (that should cause the extra arguments), or if your agent is written in python, "cat <your-simple-agent> | grep import.eossdk" (the top python file should at least make a dummy import of eossdk, even if eossdk is not used in that file directly -- this requirement is also since EOS release 4.16.6). 
By the way, which EOS and which EosSdk version are you using?

**Comment by hubertsokolowskintl** [comment]
I am using vEos 4.18.1F, my C++ application is linked with latest Eos SDK from github:
 libeos.so.1 => /lib/libeos.so.1

**Comment by tsuna** [comment]
This is just telling you the major version number.  Look in [`version.m4`](https://github.com/aristanetworks/EosSdk/blob/master/version.m4) (the last version currently is 1.10.0).

**Comment by hubertsokolowskintl** [comment]
m4_define([_VERSION_],[1.10.0])

**Comment by hubertsokolowskintl** [comment]
no extra arguments are passed to my simplified version of Random Router agent, here is the log and source code:
===== Output from /usr/local/bin/rr [] (PID=27013) started Jun  5 10:38:25.227033 ===
[AtimeLog] Initially use TA
Initializing the Random Router...
arguments 1
2017-06-05 10:38:25.937950 Using external Socket tbl://sysdb/+n
2017-06-05 10:38:25.938045 Using externally set fd: 7
on initiazlied called

source code:
class random_router : public eos::agent_handler {
 public:
   explicit random_router(eos::sdk & sdk)
      : eos::agent_handler(sdk.get_agent_mgr()) {
      printf("Initializing the Random Router...\n");
      fflush(stdout);
   }

   void on_initialized() {
      printf("on initiazlied called\n");
      fflush(stdout);
   }
};

int main(int argc, const char* argv[]) {
    eos::sdk sdk;
    random_router rr(sdk);

    printf("arguments %d\n", argc);
    for (int i = 1; i < argc; i++) {
        printf("%d argv %s\n", i, argv[i]);
    }
    sdk.main_loop(argc, const_cast<char**> (argv));
}

**Comment by hubertsokolowskintl** [comment]
The problem was with -pie linked flag that was defined in my project. With that flag the SDK failed to initialize, even though the arguments passed to my main function were passed to SDK main loop. After I disabled this flag the SDK gets initialized, but the extra arguments are not passed. According to what you have been said it should not work.
Anyway I got EOS SDK initialized successfully.

**Comment by ruferp** [comment]
Depending on the version of EOS, you will not see the extra argvs (--sysdbport etc.), they are passed via the environment (in the more recent versions).

**Comment by ruferp** [comment]
I tried the position-independent-executable option and got this error:
  /tmp/HelloWorld: undefined symbol: main
I'll assume that's the error you got too. 

I tried running a test "HelloWorld" with pie from the switch's bash (which normally hangs once the code tries to talk to sysdb, which causes lots of dots to be printed while waiting to find sysdb), and in this case I do see the dots! So the problem is in how we start the executable. 

PIE executables looks like executable shared libraries, which is actually how all our own binaries look like, and those get started by netnsd, which forks, dlopens them and dlsyms for main. main() has static linking in a pie, thus the failure.

Here to illustrate the ELF difference
python is a normal binary, Thermostat is an shared library, look at offset 16 (2="executable file", 3="share object file", see values at http://www.sco.com/developers/gabi/1998-04-29/ch4.eheader.html for example)
[admin@ol422 ~]$ od -xa /usr/bin/python | head -n 3
0000000    457f    464c    0101    0001    0000    0000    0000    0000
        del   E   L   F soh soh soh nul nul nul nul nul nul nul nul nul
0000020    0002    0003    0001    0000    857d    0804    0034    0000
[admin@ol422 ~]$ od -xa /usr/bin/Thermostat | head -n 3
0000000    457f    464c    0101    0001    0000    0000    0000    0000
        del   E   L   F soh soh soh nul nul nul nul nul nul nul nul nul
0000020    0003    0003    0001    0000    1218    0000    0034    0000

We would need to change EOS to detect this new case and simply execvp it.

**Comment by hubertsokolowskintl** [comment]
Thank you so much for explaining this to me. Now it makes sense.
I was not getting the error with undefined symbol: main. It was running fine, but the difference was with the arguments being passed to my main function.
Also I am starting my application only from the CLI, not from bash.
Actually my agent does not need to be compiled with -pie option, so I have removed it from my cmake script and there is no problem anymore. It was a good lesson though :).

Regards,
Hubert
