### ISSUE TITLE
Inconsistent behaviour adding IPv6 addresses

### ISSUE THREAD

**Issue by jta** [aristanetworks/EosSdk#9]
Hi,

I've run against some issues when testing eos sdk. I'm testing 1.7.0 on the 4.15.0F vEOS image:

```
Software image version: 4.15.0F
Architecture:           i386
Internal build version: 4.15.0F-2387143.4150F
Internal build ID:      1d97861d-09c7-4fc3-b38d-a98c99b77ae9
...
Name                                       Version/Release           Status extension
------------------------------------------ ------------------------- ------ ----
eossdk.rpm                                 1.7.0/2692785.gaatlantaeo A, I      1
```

In my toy example I add an IPv4 address to an interface, flush the event loop and verify I can observe the address when asking for a list of configured IPs. This works as expected. If I try to do the same for IPv6 however the address fails to show up the first time round: 

```py
import eossdk
sdk = eossdk.Sdk('test')

ip_intf_mgr = sdk.get_ip_intf_mgr()
eth_intf_mgr = sdk.get_eth_intf_mgr()

loop = sdk.get_event_loop()
loop.wait_for_initialized()

intfid = eossdk.IntfId('Ethernet1')

eth_intf_mgr.switchport_mode_is(intfid, eossdk.SWITCHPORT_MODE_ROUTED)
loop.flush()
assert eth_intf_mgr.switchport_mode(intfid) == eossdk.SWITCHPORT_MODE_ROUTED

def add_addr(addr, pxlen):
    ipaddr = eossdk.IpAddrMask(eossdk.IpAddr(addr), int(pxlen))
    try:
        ip_intf_mgr.ip_addr_add(intfid, ipaddr)
    except eossdk.AddressOverlapError:
        pass
    loop.flush()
    return set(a.to_string() for a in ip_intf_mgr.ip_addrs(intfid))

assert '10.0.0.1/255.255.255.255' in add_addr('10.0.0.1', 32)
if '2001:db8::1/64' not in add_addr('2001:db8::1', 64):
    print "Failed: ", ', '.join(a.to_string() for a in ip_intf_mgr.ip_addrs(intfid))
```

The result I see is:

```
localhost(config-if-Et1)#show active interface Ethernet1
localhost(config-if-Et1)#bash python test.py
Failed. Observed IPs:  10.0.0.1/255.255.255.255
localhost(config-if-Et1)#show active 
interface Ethernet1
   no switchport
   ip address 10.0.0.1/32
   ipv6 address 2001:db8::1/64
```

**Comment by rmadsen** [comment]
The `ip_addrs()` command actually describes the IP addresses in interface's `status`. While `show active` describes the config, the call you're making asks to see what addresses have been processed and applied to that interface.

Is your test consistently reproducible? If you changed `loop.flush()` to `loop.run(1)`, I'd imagine the getter would show your newly configured addresses in the status.

**Comment by jta** [comment]
It is reproducible. Funnily enough I did try `loop.run(1)` and got the same result, but retrying just now with `loop.run(2)` worked for me. I would have expected `flush` to block until all queued events were completely processed. Is there a recommended way to wait for status to reflect the change without waiting for arbitrary amounts of time?

**Comment by tsuna** [comment]
`flush` will flush everything up to Sysdb, but then bear in mind that state is replicated asynchronously across the system.  Once Sysdb gets the update, it dispatches to whoever else was subscribed to what was updated.  Then that somebody else reacts to the change and does something (such as configuring an additional IP address).  And when they do this, they send another update to Sysdb to reflect the change they made.  And that update then is propagated down to you.

So it's an asynchronous eventually consistent system.  In such a system, flushing just means you passed the memo on to the next guy, and nothing else.  `loop.run(2)` might be enough now because of timing, there is no guarantee that `loop.run(N)` of any number `N >= 1` will be enough for you to observe the status update, since it depends on how long it takes for the other agent reacting to the change you made to actually react to the change you made.

You need to wait asynchronously for the status to change, not wait any fixed amount of time or number of iterations of `run()`.

Makes sense?

**Comment by rmadsen** [comment]
`loop.flush()` waits for for your outgoing updates to be flushed through the socket to Sysdb. It has no knowledge about the underlying state tree and the relationship between config and status.

You can do something like this:

```py
class IpIntfReactor(eossdk.IpIntfHandler):
   def __init__(self, mgr, intf):
      eossdk.IpIntfHandler.__init__(self, mgr)
      self.watch_ip_intf(intf, True)
      self.done = False

   def on_ip_addr_add(self, intf, maskedAddr):
      # Maybe add a check that the addr is the one you care about
      self.done = True

ipIntfReactor = IpIntfReactor(ip_intf_mgr, intfid)
add_addr('2001:db8::1', 64)
while not ipIntfReactor.done:
   loop.run(0.1)
```
(I haven't tested this, so you may find a bug or two in this example code).

**Comment by jta** [comment]
Yea, makes sense, thanks. This actually doesn't impact my expected use case, since that is inherently asynchronous. The only case where I run into evaluating step by step is in my existing tests, which I'm currently porting over. Thanks for clarifying on that, feel free to close!
